export const PROJECT_CATEGORIES = ['All', 'Celebrations', 'Holidays', 'Travel', 'Seasonal'];

export const PROJECT_TEMPLATES = [
  {
    id: 'proj-bday',
    name: 'Birthday Party Planning',
    description: 'Complete checklist for planning and executing a child\'s birthday party.',
    category: 'Celebrations',
    defaultDurationDays: 21,
    timeline: '3 weeks before to party day',
    estimatedTotalHours: 20,
    subtasks: [
      { id: 'bday-1', phase: 'Planning — 3 weeks before', task: 'Decide on party date, time, and location', description: 'Choose venue (home, park, venue rental), check availability', daysBeforeEvent: 21, estimatedMinutes: 30, priority: 'high' },
      { id: 'bday-2', phase: 'Planning — 3 weeks before', task: 'Determine guest list and create invite list', description: 'Decide who to invite, get contact information. Consider kids vs. adult supervision ratio.', daysBeforeEvent: 21, estimatedMinutes: 45, priority: 'high' },
      { id: 'bday-3', phase: 'Planning — 3 weeks before', task: 'Set budget for party', description: 'Determine total spending limit, allocate to food, decorations, entertainment, party favors.', daysBeforeEvent: 21, estimatedMinutes: 20, priority: 'medium' },
      { id: 'bday-4', phase: 'Planning — 3 weeks before', task: 'Plan party theme and activities', description: 'Choose theme, plan games, crafts, or entertainment based on birthday child\'s interests.', daysBeforeEvent: 21, estimatedMinutes: 60, priority: 'high' },
      { id: 'bday-5', phase: 'Invitations — 2.5 weeks before', task: 'Create and send invitations', description: 'Digital or paper invites with RSVP deadline. Include date, time, location, and any special instructions.', daysBeforeEvent: 14, estimatedMinutes: 45, priority: 'high' },
      { id: 'bday-6', phase: 'Planning — 2 weeks before', task: 'Plan menu and cake design', description: 'Decide on food, snacks, cake design, dietary restrictions. Ask about food allergies in RSVP.', daysBeforeEvent: 14, estimatedMinutes: 60, priority: 'high' },
      { id: 'bday-7', phase: 'Planning — 2 weeks before', task: 'Order cake or plan to bake', description: 'Order from bakery or schedule baking time. Order early for custom designs.', daysBeforeEvent: 14, estimatedMinutes: 15, priority: 'high' },
      { id: 'bday-8', phase: 'Planning — 2 weeks before', task: 'Create shopping list for food and supplies', description: 'List all groceries, decorations, supplies needed. Organize by store section.', daysBeforeEvent: 14, estimatedMinutes: 45, priority: 'medium' },
      { id: 'bday-9', phase: 'Preparations — 1 week before', task: 'Buy decorations and party supplies', description: 'Purchase balloons, streamers, plates, cups, napkins, etc.', daysBeforeEvent: 7, estimatedMinutes: 90, priority: 'medium' },
      { id: 'bday-10', phase: 'Preparations — 1 week before', task: 'Shop for food and ingredients', description: 'Purchase all food items. Buy perishables 1–2 days before, frozen items earlier.', daysBeforeEvent: 7, estimatedMinutes: 120, priority: 'high' },
      { id: 'bday-11', phase: 'Preparations — 1 week before', task: 'Prepare or order party favors', description: 'Assemble or purchase goodie bags / party favors.', daysBeforeEvent: 7, estimatedMinutes: 90, priority: 'low' },
      { id: 'bday-12', phase: 'Preparations — 3 days before', task: 'Plan party timeline and schedule', description: 'Create minute-by-minute schedule: arrival, activities, food, cake, cleanup.', daysBeforeEvent: 3, estimatedMinutes: 30, priority: 'medium' },
      { id: 'bday-13', phase: 'Preparations — 3 days before', task: 'Prepare home or venue for party', description: 'Deep clean, move furniture, create party space.', daysBeforeEvent: 3, estimatedMinutes: 120, priority: 'medium' },
      { id: 'bday-14', phase: 'Day before', task: 'Food prep and setup', description: 'Prep food that can be made ahead, set up tables. Prepare dips, cut fruit, arrange platters (covered).', daysBeforeEvent: 1, estimatedMinutes: 180, priority: 'high' },
      { id: 'bday-15', phase: 'Day before', task: 'Decorate party space', description: 'Hang decorations, arrange tables, set up activity stations.', daysBeforeEvent: 1, estimatedMinutes: 120, priority: 'medium' },
      { id: 'bday-16', phase: 'Party day', task: 'Final food prep and drinks setup', description: 'Finish food prep, set up drink station, arrange snacks. Do 1 hour before guests arrive.', daysBeforeEvent: 0, estimatedMinutes: 90, priority: 'high' },
      { id: 'bday-17', phase: 'Party day', task: 'Final venue check', description: 'Bathroom check, music setup, activity station check. Do 30 minutes before guests arrive.', daysBeforeEvent: 0, estimatedMinutes: 30, priority: 'high' },
      { id: 'bday-18', phase: 'Party day', task: 'Execute party and manage activities', description: 'Run the party, manage activities, supervise games. Stay flexible, have backup activities ready.', daysBeforeEvent: 0, estimatedMinutes: 180, priority: 'high' },
      { id: 'bday-19', phase: 'After party', task: 'Cleanup and storage', description: 'Clear decorations, clean up food, restore furniture. Can spread over 1–2 days.', daysBeforeEvent: 0, estimatedMinutes: 120, priority: 'medium' },
      { id: 'bday-20', phase: 'After party', task: 'Send thank you notes', description: 'Write thank you notes to attendees for gifts and help. Do within one week of party.', daysBeforeEvent: -3, estimatedMinutes: 45, priority: 'low' },
    ],
  },
  {
    id: 'proj-christmas',
    name: 'Christmas Holiday Preparation',
    description: 'Complete planning for Christmas holidays from November through December.',
    category: 'Holidays',
    defaultDurationDays: 56,
    timeline: '8 weeks before Christmas',
    estimatedTotalHours: 40,
    subtasks: [
      { id: 'xmas-1', phase: 'November — 8 weeks before', task: 'Set Christmas budget', description: 'Determine spending for gifts, decorations, food, travel, teacher/staff gifts.', daysBeforeEvent: 56, estimatedMinutes: 30, priority: 'high' },
      { id: 'xmas-2', phase: 'November — 8 weeks before', task: 'Plan gift list for entire family', description: 'Create list of who to buy for with gift ideas. Include kids, grandparents, siblings, teachers, neighbors.', daysBeforeEvent: 56, estimatedMinutes: 60, priority: 'high' },
      { id: 'xmas-3', phase: 'November — 8 weeks before', task: 'Create Christmas card list', description: 'Compile mailing addresses or email list for holiday cards.', daysBeforeEvent: 56, estimatedMinutes: 45, priority: 'low' },
      { id: 'xmas-4', phase: 'November — 6 weeks before', task: 'Start Christmas shopping', description: 'Purchase gifts, especially large or hard-to-find items. Shop early for best selection.', daysBeforeEvent: 42, estimatedMinutes: 240, priority: 'high' },
      { id: 'xmas-5', phase: 'November — 6 weeks before', task: 'Plan holiday menu and recipes', description: 'Decide on Christmas dinner, sides, desserts, appetizers. Consider guest dietary restrictions.', daysBeforeEvent: 42, estimatedMinutes: 90, priority: 'medium' },
      { id: 'xmas-6', phase: 'Early December — 4 weeks before', task: 'Wrap and organize gifts', description: 'Wrap gifts as purchased, organize by recipient. Keep wrapping supplies and list organized.', daysBeforeEvent: 28, estimatedMinutes: 180, priority: 'medium' },
      { id: 'xmas-7', phase: 'Early December — 4 weeks before', task: 'Plan holiday party or gathering', description: 'Plan host date, guest list, menu, activities if hosting.', daysBeforeEvent: 28, estimatedMinutes: 90, priority: 'medium' },
      { id: 'xmas-8', phase: 'Early December — 4 weeks before', task: 'Decorate home interior', description: 'Put up Christmas tree, garland, lights, stockings, mantels.', daysBeforeEvent: 28, estimatedMinutes: 120, priority: 'medium' },
      { id: 'xmas-9', phase: 'Early December — 4 weeks before', task: 'Decorate home exterior', description: 'Hang outdoor lights, inflatables, wreaths, landscaping. Safety first with ladder and electrical work.', daysBeforeEvent: 28, estimatedMinutes: 180, priority: 'low' },
      { id: 'xmas-10', phase: 'Mid-December — 2 weeks before', task: 'Send holiday cards', description: 'Write, address, and mail Christmas cards. Mail by mid-December to arrive on time.', daysBeforeEvent: 14, estimatedMinutes: 120, priority: 'low' },
      { id: 'xmas-11', phase: 'Mid-December — 2 weeks before', task: 'Plan holiday activities and traditions', description: 'Plan movie nights, baking, outings, family traditions.', daysBeforeEvent: 14, estimatedMinutes: 45, priority: 'medium' },
      { id: 'xmas-12', phase: 'Mid-December — 2 weeks before', task: 'Create Christmas morning plan', description: 'Plan gift opening schedule, breakfast, activities.', daysBeforeEvent: 14, estimatedMinutes: 30, priority: 'medium' },
      { id: 'xmas-13', phase: 'Mid-December — 10 days before', task: 'Grocery shop for holiday meals', description: 'Purchase non-perishables early, perishables closer to the date. Shop early to avoid crowds.', daysBeforeEvent: 10, estimatedMinutes: 120, priority: 'high' },
      { id: 'xmas-14', phase: '1 week before', task: 'Prep and freeze holiday food', description: 'Make stocks, sauces, baked goods — dishes that can be frozen ahead.', daysBeforeEvent: 7, estimatedMinutes: 180, priority: 'medium' },
      { id: 'xmas-15', phase: '1 week before', task: 'Clean and prepare home for guests', description: 'Deep clean, prepare guest rooms, organize bathrooms.', daysBeforeEvent: 7, estimatedMinutes: 240, priority: 'medium' },
      { id: 'xmas-16', phase: '1 week before', task: 'Purchase last-minute gifts and stocking stuffers', description: 'Buy any remaining gifts, forgotten items, stocking stuffers.', daysBeforeEvent: 7, estimatedMinutes: 90, priority: 'medium' },
      { id: 'xmas-17', phase: '2–3 days before', task: 'Final food prep and setup', description: 'Prepare dishes that can be made ahead, set tables.', daysBeforeEvent: 3, estimatedMinutes: 180, priority: 'high' },
      { id: 'xmas-18', phase: '1 day before', task: 'Final clean and arrange decorations', description: 'Tidy up, arrange flowers, final decoration touches.', daysBeforeEvent: 1, estimatedMinutes: 120, priority: 'medium' },
      { id: 'xmas-19', phase: 'Christmas Eve', task: 'Set up gift presentation', description: 'Arrange gifts under tree, fill stockings, set the scene.', daysBeforeEvent: 0, estimatedMinutes: 90, priority: 'high' },
      { id: 'xmas-20', phase: 'Christmas Eve', task: 'Final meal preparations', description: 'Heat up prepped dishes, final cooking, set table.', daysBeforeEvent: 0, estimatedMinutes: 120, priority: 'high' },
      { id: 'xmas-21', phase: 'After Christmas', task: 'Cleanup and storage', description: 'Clear dishes, store decorations, return home to normal. Can spread over several days.', daysBeforeEvent: -1, estimatedMinutes: 180, priority: 'medium' },
    ],
  },
  {
    id: 'proj-vacation',
    name: 'Vacation Planning & Packing',
    description: 'Complete checklist for planning a family vacation and packing.',
    category: 'Travel',
    defaultDurationDays: 42,
    timeline: '6 weeks before departure',
    estimatedTotalHours: 25,
    subtasks: [
      { id: 'vac-1', phase: '6 weeks before', task: 'Decide vacation destination and dates', description: 'Choose location, dates, length of stay. Consider kids\' schedules, weather, family preferences.', daysBeforeEvent: 42, estimatedMinutes: 45, priority: 'high' },
      { id: 'vac-2', phase: '6 weeks before', task: 'Set vacation budget', description: 'Determine spending limit for flights, lodging, activities, food.', daysBeforeEvent: 42, estimatedMinutes: 30, priority: 'high' },
      { id: 'vac-3', phase: '6 weeks before', task: 'Book flights and accommodations', description: 'Reserve flights, hotel, rental home, or other lodging. Book early for best rates.', daysBeforeEvent: 42, estimatedMinutes: 60, priority: 'high' },
      { id: 'vac-4', phase: '5 weeks before', task: 'Research destination and activities', description: 'Find attractions, restaurants, family-friendly activities, safety info.', daysBeforeEvent: 35, estimatedMinutes: 90, priority: 'medium' },
      { id: 'vac-5', phase: '5 weeks before', task: 'Plan itinerary and activities', description: 'Create rough schedule of what to do each day. Leave flexibility for spontaneity.', daysBeforeEvent: 35, estimatedMinutes: 60, priority: 'medium' },
      { id: 'vac-6', phase: '5 weeks before', task: 'Book reservations', description: 'Reserve rental cars, tours, restaurants, attractions. Book popular spots early.', daysBeforeEvent: 35, estimatedMinutes: 75, priority: 'medium' },
      { id: 'vac-7', phase: '4 weeks before', task: 'Check and renew travel documents', description: 'Verify passports are valid for all family members, renew if needed. International travel needs 6+ months validity.', daysBeforeEvent: 28, estimatedMinutes: 30, priority: 'high' },
      { id: 'vac-8', phase: '4 weeks before', task: 'Schedule medical/dental checkups if needed', description: 'Ensure family is healthy, get prescriptions refilled.', daysBeforeEvent: 28, estimatedMinutes: 30, priority: 'medium' },
      { id: 'vac-9', phase: '3 weeks before', task: 'Create packing list', description: 'List clothing, shoes, toiletries, medications for each person. Organize by person and category.', daysBeforeEvent: 21, estimatedMinutes: 75, priority: 'high' },
      { id: 'vac-10', phase: '2 weeks before', task: 'Arrange childcare or pet care', description: 'Arrange pet sitters, house plant care, home security.', daysBeforeEvent: 14, estimatedMinutes: 30, priority: 'high' },
      { id: 'vac-11', phase: '2 weeks before', task: 'Prepare home for absence', description: 'Cancel mail, adjust thermostat, secure valuables, arrange cleaning.', daysBeforeEvent: 14, estimatedMinutes: 45, priority: 'medium' },
      { id: 'vac-12', phase: '2 weeks before', task: 'Arrange airport transport or parking', description: 'Book taxi, rideshare, airport parking, or rental car.', daysBeforeEvent: 14, estimatedMinutes: 30, priority: 'high' },
      { id: 'vac-13', phase: '1 week before', task: 'Shop for travel items and snacks', description: 'Buy travel games, snacks, entertainment, comfort items.', daysBeforeEvent: 7, estimatedMinutes: 60, priority: 'low' },
      { id: 'vac-14', phase: '1 week before', task: 'Laundry and clothing prep', description: 'Wash everything that will be packed.', daysBeforeEvent: 7, estimatedMinutes: 120, priority: 'high' },
      { id: 'vac-15', phase: '1 week before', task: 'Prepare medications and health items', description: 'Gather medications, first aid kit, sunscreen, bug spray.', daysBeforeEvent: 7, estimatedMinutes: 45, priority: 'high' },
      { id: 'vac-16', phase: '3 days before', task: 'Gather toiletries and personal care items', description: 'Toothbrushes, toothpaste, shampoo, deodorant, etc. Use small bottles or buy travel sizes.', daysBeforeEvent: 3, estimatedMinutes: 45, priority: 'medium' },
      { id: 'vac-17', phase: '2 days before', task: 'Charge all electronic devices', description: 'Charge phones, tablets, cameras. Pack chargers and adapters.', daysBeforeEvent: 2, estimatedMinutes: 15, priority: 'high' },
      { id: 'vac-18', phase: '1 day before', task: 'Pack suitcases', description: 'Pack all luggage according to packing list. Weigh luggage to avoid overage fees.', daysBeforeEvent: 1, estimatedMinutes: 180, priority: 'high' },
      { id: 'vac-19', phase: '1 day before', task: 'Prepare carry-on bags', description: 'Pack snacks, entertainment, valuables, medications in carry-on.', daysBeforeEvent: 1, estimatedMinutes: 60, priority: 'high' },
      { id: 'vac-20', phase: '1 day before', task: 'Final home prep', description: 'Turn off lights, lock doors, adjust temperature, prep for return.', daysBeforeEvent: 1, estimatedMinutes: 45, priority: 'medium' },
      { id: 'vac-21', phase: 'Travel day', task: 'Final checks and departure', description: 'Check tickets, boarding passes, passports. Arrive 2–3 hours early for flights.', daysBeforeEvent: 0, estimatedMinutes: 90, priority: 'high' },
      { id: 'vac-22', phase: 'After return', task: 'Unpack and laundry', description: 'Unpack luggage, start laundry, put away items.', daysBeforeEvent: -1, estimatedMinutes: 120, priority: 'medium' },
    ],
  },
  {
    id: 'proj-backtoschool',
    name: 'Back to School Preparation',
    description: 'Complete checklist for back-to-school shopping and preparation.',
    category: 'Seasonal',
    defaultDurationDays: 42,
    timeline: '6 weeks before school starts',
    estimatedTotalHours: 30,
    subtasks: [
      { id: 'bts-1', phase: '6 weeks before', task: 'Confirm school start date and schedule', description: 'Get school calendar, class times, teacher assignments.', daysBeforeEvent: 42, estimatedMinutes: 20, priority: 'high' },
      { id: 'bts-2', phase: '6 weeks before', task: 'Set back-to-school budget', description: 'Determine spending for clothes, shoes, supplies, lunches, technology.', daysBeforeEvent: 42, estimatedMinutes: 30, priority: 'high' },
      { id: 'bts-3', phase: '5 weeks before', task: 'Get required school supply list', description: 'Obtain supply list from school or teacher.', daysBeforeEvent: 35, estimatedMinutes: 15, priority: 'high' },
      { id: 'bts-4', phase: '5 weeks before', task: 'Shop for clothing and shoes', description: 'Buy school clothes, shoes, jackets for each child. Include weather-appropriate items.', daysBeforeEvent: 35, estimatedMinutes: 120, priority: 'high' },
      { id: 'bts-5', phase: '4 weeks before', task: 'Shop for school supplies', description: 'Purchase pencils, notebooks, folders, backpacks, lunch supplies. Buy during sales.', daysBeforeEvent: 28, estimatedMinutes: 90, priority: 'high' },
      { id: 'bts-6', phase: '4 weeks before', task: 'Label all items with names', description: 'Label clothes, shoes, lunch items, supplies with permanent marker or labels.', daysBeforeEvent: 28, estimatedMinutes: 120, priority: 'medium' },
      { id: 'bts-7', phase: '3 weeks before', task: 'Schedule haircuts', description: 'Book appointments for back-to-school haircuts.', daysBeforeEvent: 21, estimatedMinutes: 15, priority: 'low' },
      { id: 'bts-8', phase: '3 weeks before', task: 'Schedule medical and dental appointments', description: 'Eye exams, physical exams, dental checkups, vaccinations. Many schools require physical forms.', daysBeforeEvent: 21, estimatedMinutes: 30, priority: 'medium' },
      { id: 'bts-9', phase: '2 weeks before', task: 'Complete school enrollment forms', description: 'Fill out all required school registration and medical forms.', daysBeforeEvent: 14, estimatedMinutes: 60, priority: 'high' },
      { id: 'bts-10', phase: '2 weeks before', task: 'Set up lunch plan', description: 'Decide on packed lunch, school lunch, or combination. Buy lunch containers, plan easy lunches.', daysBeforeEvent: 14, estimatedMinutes: 45, priority: 'medium' },
      { id: 'bts-11', phase: '1 week before', task: 'Practice new schedule', description: 'Start adjusting sleep schedule and morning routine. Move bedtime earlier gradually.', daysBeforeEvent: 7, estimatedMinutes: 30, priority: 'medium' },
      { id: 'bts-12', phase: '1 week before', task: 'Organize school supplies and backpack', description: 'Set up desk, organize backpack, label compartments.', daysBeforeEvent: 7, estimatedMinutes: 60, priority: 'medium' },
      { id: 'bts-13', phase: '1 week before', task: 'Plan school morning routine', description: 'Create and practice morning schedule with kids: wake up, breakfast, dressing, leaving on time.', daysBeforeEvent: 7, estimatedMinutes: 45, priority: 'medium' },
      { id: 'bts-14', phase: '3 days before', task: 'Wash and dry all new clothing', description: 'Launder clothes, fold, organize in drawers.', daysBeforeEvent: 3, estimatedMinutes: 120, priority: 'medium' },
      { id: 'bts-15', phase: 'Day before', task: 'Pack backpacks and prepare for first day', description: 'Pack supplies, snacks, lunch. Lay out first day outfit.', daysBeforeEvent: 1, estimatedMinutes: 60, priority: 'high' },
    ],
  },
  {
    id: 'proj-holidaymeal',
    name: 'Holiday Meal Preparation',
    description: 'Complete planning and prep for a major holiday meal (Thanksgiving, Easter, etc.).',
    category: 'Holidays',
    defaultDurationDays: 21,
    timeline: '3 weeks before holiday',
    estimatedTotalHours: 25,
    subtasks: [
      { id: 'hmeal-1', phase: '3 weeks before', task: 'Create guest list and confirm attendance', description: 'Decide who\'s coming, get final headcount.', daysBeforeEvent: 21, estimatedMinutes: 30, priority: 'high' },
      { id: 'hmeal-2', phase: '3 weeks before', task: 'Plan menu with recipes', description: 'Decide on main dish, sides, desserts, drinks. Ask about dietary restrictions.', daysBeforeEvent: 21, estimatedMinutes: 90, priority: 'high' },
      { id: 'hmeal-3', phase: '2 weeks before', task: 'Create detailed shopping list', description: 'List all ingredients organized by store section.', daysBeforeEvent: 14, estimatedMinutes: 60, priority: 'high' },
      { id: 'hmeal-4', phase: '2 weeks before', task: 'Assign side dishes to guests', description: 'Coordinate who brings what to prevent duplicates.', daysBeforeEvent: 14, estimatedMinutes: 30, priority: 'low' },
      { id: 'hmeal-5', phase: '1 week before', task: 'Shop for non-perishable items', description: 'Buy canned goods, spices, wines, non-perishables early.', daysBeforeEvent: 7, estimatedMinutes: 90, priority: 'high' },
      { id: 'hmeal-6', phase: '1 week before', task: 'Prepare home for guests', description: 'Deep clean, set table, prepare guest areas.', daysBeforeEvent: 7, estimatedMinutes: 120, priority: 'medium' },
      { id: 'hmeal-7', phase: '3 days before', task: 'Shop for perishable items', description: 'Buy meat, fresh vegetables, dairy, last-minute items.', daysBeforeEvent: 3, estimatedMinutes: 90, priority: 'high' },
      { id: 'hmeal-8', phase: '2 days before', task: 'Prep vegetables and make-ahead dishes', description: 'Chop vegetables, make soups, sauces, prep sides.', daysBeforeEvent: 2, estimatedMinutes: 180, priority: 'high' },
      { id: 'hmeal-9', phase: '1 day before', task: 'Final food prep and setup', description: 'Finish prepped dishes, set table completely.', daysBeforeEvent: 1, estimatedMinutes: 150, priority: 'high' },
      { id: 'hmeal-10', phase: 'Holiday day', task: 'Morning cooking', description: 'Start main dish, finish time-sensitive dishes. Follow timeline for coordinating cooking.', daysBeforeEvent: 0, estimatedMinutes: 180, priority: 'high' },
      { id: 'hmeal-11', phase: 'Holiday day', task: 'Final garnishing and serving', description: 'Plate food, final touches, arrange on serving platters.', daysBeforeEvent: 0, estimatedMinutes: 60, priority: 'high' },
      { id: 'hmeal-12', phase: 'After meal', task: 'Cleanup and storage', description: 'Clear dishes, store leftovers, clean kitchen. Can spread over 1–2 days.', daysBeforeEvent: 0, estimatedMinutes: 120, priority: 'medium' },
    ],
  },
  {
    id: 'proj-summbreak',
    name: 'Summer Break Planning',
    description: 'Plan activities, camps, and childcare for summer break.',
    category: 'Seasonal',
    defaultDurationDays: 60,
    timeline: '2 months before summer starts',
    estimatedTotalHours: 20,
    subtasks: [
      { id: 'sum-1', phase: '8 weeks before', task: 'Check school end dates and plan coverage', description: 'Confirm last day of school, plan childcare and activities coverage.', daysBeforeEvent: 56, estimatedMinutes: 30, priority: 'high' },
      { id: 'sum-2', phase: '8 weeks before', task: 'Research summer camps and programs', description: 'Look into day camps, specialty camps, sports camps.', daysBeforeEvent: 56, estimatedMinutes: 90, priority: 'high' },
      { id: 'sum-3', phase: '6 weeks before', task: 'Book summer camps and activities', description: 'Enroll kids in camps, classes, sports programs. Popular programs fill up early.', daysBeforeEvent: 42, estimatedMinutes: 75, priority: 'high' },
      { id: 'sum-4', phase: '6 weeks before', task: 'Arrange childcare for non-scheduled days', description: 'Hire nanny, babysitter, or arrange playdates for gaps.', daysBeforeEvent: 42, estimatedMinutes: 60, priority: 'high' },
      { id: 'sum-5', phase: '4 weeks before', task: 'Plan family outings and trips', description: 'Research parks, museums, pools, beaches, family activities.', daysBeforeEvent: 28, estimatedMinutes: 75, priority: 'medium' },
      { id: 'sum-6', phase: '4 weeks before', task: 'Create summer activity list for home', description: 'Plan crafts, games, movie days, baking projects for downtime.', daysBeforeEvent: 28, estimatedMinutes: 60, priority: 'medium' },
      { id: 'sum-7', phase: '3 weeks before', task: 'Plan summer reading program participation', description: 'Sign up for library programs, select books for kids.', daysBeforeEvent: 21, estimatedMinutes: 45, priority: 'low' },
      { id: 'sum-8', phase: '2 weeks before', task: 'Prepare camp supplies and equipment', description: 'Buy water bottles, snacks, bug spray, sunscreen.', daysBeforeEvent: 14, estimatedMinutes: 60, priority: 'medium' },
      { id: 'sum-9', phase: '1 week before', task: 'Label camp supplies and gear', description: 'Mark all belongings sent to camps with child\'s name.', daysBeforeEvent: 7, estimatedMinutes: 45, priority: 'medium' },
      { id: 'sum-10', phase: '1 week before', task: 'Set up summer schedule and routine', description: 'Create visual schedule for kids showing activities and commitments.', daysBeforeEvent: 7, estimatedMinutes: 45, priority: 'medium' },
    ],
  },
];

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };

/**
 * Creates a project object from a template.
 * eventDate: ISO date string of the event/target date (e.g. "2026-12-25")
 * customName: optional override for the project title
 */
export function createProjectFromTemplate(template, eventDate, customName) {
  const base = new Date(eventDate + 'T12:00:00');

  const subtasks = [...template.subtasks]
    .sort((a, b) => (b.daysBeforeEvent - a.daysBeforeEvent) || (PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]))
    .map(st => {
      const due = new Date(base);
      due.setDate(due.getDate() - st.daysBeforeEvent);
      return {
        id: `${st.id}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        text: st.task,
        completed: false,
        dueDate: due.toISOString().split('T')[0],
        notes: st.description,
        phase: st.phase,
        priority: st.priority,
        estimatedMinutes: st.estimatedMinutes,
      };
    });

  return {
    id: `proj-${Date.now()}`,
    title: customName || template.name,
    description: template.description,
    status: 'active',
    dueDate: eventDate,
    subtasks,
    notes: `Created from template: ${template.name}. Timeline: ${template.timeline}.`,
  };
}
